INSERT INTO programs (title, description, trait) VALUES
('Tölvunarfræði', 'Fyrir þá sem elska rökhugsun, forritun og lausnamiðaða hugsun.', 'analytical'),
('Grafísk hönnun', 'Fyrir skapandi einstaklinga með áhuga á sjónrænni framsetningu.', 'creative'),
('Sjúkraþjálfun', 'Fyrir þau sem vilja hjálpa fólki og vinna með heilsu.', 'social'),
('Rafvirki', 'Fyrir verklega og tæknilega sinnað fólk sem vill vinna með búnað og kerfi.', 'hands'),
('Hugbúnaðarverkfræði', 'Forritun og kerfi.', 'analytical'),
('Myndlist', 'Skapandi list.', 'creative'),
('Kvikmyndagerð', 'Video og miðlun.', 'creative'),
('Sálfræði', 'Fólk og hugsun.', 'social'),
('Smíði', 'Handavinna og byggingar.', 'hands'),
('Verkfræði', 'Stærðfræði og tæknilausnir.', 'analytical'),
('Viðskiptafræði', 'Viðskipti, rekstur og skipulag.', 'social');

INSERT INTO program_schools (program_id, school_name, link) VALUES
(1, 'Háskóli Íslands', 'https://hi.is/tolvunarfraedi'),
(1, 'Háskólinn í Reykjavík', 'https://www.ru.is/deildir/tolvunarfraedideild/tolvunarfraedi'),
(2, 'Listaháskóli Íslands', 'https://www.lhi.is/namsleid/grafisk-honnun-ba/'),
(3, 'Háskóli Íslands', 'https://hi.is/sjukrathjalfunarfraedi'),
(4, 'Tækniskólinn', 'https://tskoli.is/namsbraut/rafvirkjun/'),
(5, 'Háskóli Íslands', 'https://hi.is/hugbunadarverkfraedi'),
(5, 'Háskólinn í Reykjavík', 'https://www.ru.is'),
(6, 'Listaháskóli Íslands', 'https://www.lhi.is/namsleid/myndlist-ba/'),
(7, 'Listaháskóli Íslands', 'https://www.lhi.is/kvikmyndalistadeild/'),
(8, 'Háskóli Íslands', 'https://hi.is/salfraedi'),
(9, 'Tækniskólinn', 'https://tskoli.is/namsbraut/husasmidi/'),
(10, 'Háskóli Íslands', 'https://hi.is'),
(10, 'Háskólinn í Reykjavík', 'https://www.ru.is'),
(11, 'Háskóli Íslands', 'https://hi.is'),
(11, 'Háskólinn í Reykjavík', 'https://www.ru.is'),
(11, 'Háskólinn á Bifröst', 'https://www.bifrost.is');