INSERT INTO programs (title, description, trait, school, link) VALUES
('Tölvunarfræði 🖥️', 'Fyrir þá sem elska rökhugsun, forritun og lausnamiðaða hugsun.', 'analytical', 'Háskóli Íslands', 'https://hi.is/tolvunarfraedi'),
('Grafísk hönnun 📐', 'Fyrir skapandi einstaklinga með áhuga á sjónrænni framsetningu.', 'creative', 'Listaháskóli Íslands', 'https://www.lhi.is/namsleid/grafisk-honnun-ba/'),
('Sjúkraþjálfun 💪', 'Fyrir þau sem vilja hjálpa fólki og vinna með heilsu.', 'social', 'Háskóli Íslands', 'https://hi.is/sjukrathjalfunarfraedi'),
('Rafvirki ⚡️', 'Fyrir verklega og tæknilega sinnað fólk sem vill vinna með búnað og kerfi.', 'hands', 'Tækniskólinn', 'https://tskoli.is/namsbraut/rafvirkjun/'),
('Hugbúnaðarverkfræði 🛜', 'Fyrir þá sem vilja brúa bilið á milli verkfræðilegrar nákvæmni og flókinnar forritunar til að hanna stór og örugg tölvukerfi.', 'analytical', 'Háskóli Íslands', 'https://hi.is/hugbunadarverkfraedi'),
('Myndlist 🎨', 'Fyrir þau sem eru hugmyndarík og geta skapað list.', 'creative', 'Listaháskóli Íslands', 'https://www.lhi.is/namsleid/myndlist-ba/'),
('Kvikmyndagerð 🎬', 'Fyrir þá sem hafa ástríðu fyrir sögugerð og sjónrænni list.', 'creative', 'Listaháskóli Íslands', 'https://www.lhi.is/kvikmyndalistadeild/'),
('Sálfræði 🧠', 'Fyrir þá sem vilja skilja hugsun, hegðun og tilfinningar fólks.', 'social', 'Háskóli Íslands', 'https://hi.is/salfraedi'),
('Smíði ⚒️', 'Fyrir þá sem vilja vinna með höndunum, skapa varanlega hluti og sjá raunverulegan árangur eftir vinnudaginn.', 'hands', 'Tækniskólinn', 'https://tskoli.is/namsbraut/husasmidi/'),
('Verkfræði ⚙️', 'Fyrir þá sem vilja hanna, smíða og nýta tækni og vísindi til að leysa flóknar áskoranir raunheimsins.', 'analytical', 'Háskóli Íslands', 'https://hi.is/verkfraedi_og_natturuvisindasvid/verkfraedi'),
('Viðskiptafræði 💵', 'Fyrir þá sem hafa áhuga á rekstri, stjórnun og verðmætasköpun í síbreytilegu umhverfi.', 'social', 'Háskóli Íslands', 'https://hi.is/vidskiptafraedi_bs_180_einingar'),
('Hönnun ✨', 'Hönnun á vörum og lausnum með skapandi og verklegri nálgun.', 'creative', 'Listaháskóli Íslands', 'https://www.lhi.is/honnunardeild/'),
('Lífeindafræði 🧬', 'Vísindi, rannsóknir og vinna með heilsu og greiningar.', 'analytical', 'Háskóli Íslands', 'https://hi.is/lifeindafraedi'),
('Kennarafræði 📚', 'Fyrir þau sem vilja kenna og styðja aðra í námi.', 'social', 'Háskóli Íslands', 'https://hi.is/menntavisindasvid'),
('Vélstjórn ⚓️', 'Verklegt nám tengt vélum, kerfum og tæknibúnaði.', 'hands', 'Tækniskólinn', 'https://tskoli.is/namsbraut/velstjorn-namsstig-a/');